### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by RikaIljina** [RikaIljina/DjangoTest#3]
AC1: A model for each database table has been created
AC2: An ORM for all models has been created

**Tasks:**

- [ ] Write down model names
- [ ] Decide which fields to use
- [ ] Figure out the relation of each model to other models and note the foreign keys
